-- AlterTable
ALTER TABLE "MessageIntent" ADD COLUMN     "earliestSendAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "preferredSendAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
